runtime: nodejs12
instance_class: F4

handlers:
- url: .*
  secure: always
  script: auto

includes:
  - secret_env_vars.yaml

env_variables:
  ACTION_HUB_LABEL: 'Advanced Analytics Accelerator'
  PORT: '8080'
  ACTION_DEBUG: '0'
  ACTION_WHITELIST: 'google_cloud_storage,google_automl_table,nifi'


automatic_scaling:
  max_instances: 3
